apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: ticketing-microservices
build:
  artifacts:
    - image: eldoghry/ticketing-auth
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-controller.yaml
