apiVersion: apps/v1
kind: Deployment # Pod | Deployment | Service
metadata:
  name: front-depl # name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-front # match all pods with name auth
  template:
    metadata:
      labels:
        app: ticketing-front
    spec:
      containers:
        - name: ticketing-front
          image: eldoghry/ticketing-front:latest # can use specific tag eldoghry/front:0.0.3
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-front-cluster-ip-srv
spec:
  type: ClusterIP # default is ClusterIP [ClusterIP | NodePort | LoadBalancer | ExternalName]
  selector:
    app: ticketing-front
  ports:
    - name: ticketing-front
      protocol: TCP
      port: 3000 # node accept request on this port
      targetPort: 3000 # request will forward to pod on this port
